# Generated by Django 3.0.3 on 2020-02-09 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_auto_20200209_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Создан'), ('waiting_for_capture', 'Ожидает подтверждения от пользователя'), ('succeeded', 'Успешно оплачен'), ('canceled', 'Отменен')], default='pending', max_length=40, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('account', 'Подтверждение аккаунта'), ('deposit', 'Депозит'), ('full', 'Полная стоимость'), ('usercard', 'Оплата картой клиента')], default='account', max_length=40, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Транзакции',
                'verbose_name_plural': 'Транзакции',
            },
            managers=[
                ('yandex', django.db.models.manager.Manager()),
            ],
        ),
    ]
