# Generated by Django 3.0.3 on 2020-02-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='payment_status',
        ),
    ]
