# Generated by Django 3.0.3 on 2020-02-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_transactions_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='checkouted',
            field=models.BooleanField(default=False),
        ),
    ]
