# Generated by Django 3.0.3 on 2020-02-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transactions_checkouted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('account', 'Привязка карты'), ('deposit', 'Депозит'), ('full', 'Полная стоимость'), ('usercard', 'Оплата картой клиента')], default='account', max_length=40, null=True),
        ),
    ]
