# Generated by Django 3.0.3 on 2020-02-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='phone_number',
            field=models.CharField(default='', max_length=50, verbose_name='Телефонный номер'),
        ),
    ]
