# Generated by Django 3.0.3 on 2020-02-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200210_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='ref_link',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
