# Generated by Django 3.0.3 on 2020-02-08 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_auto_20200208_1912'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=None, null=True, verbose_name='Начало аренды')),
                ('end', models.DateTimeField(default=None, null=True, verbose_name='Окончание аренды')),
                ('booking_end', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Окончание бронироваия')),
                ('status', models.BooleanField(default=False, null=True)),
                ('paid', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('trial_key', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Квартира', related_query_name='Квартира', to='catalog.Flats')),
                ('rentor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
                'ordering': ['-start'],
            },
        ),
    ]
