# Generated by Django 3.0.3 on 2020-02-09 15:47

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='booking',
            managers=[
                ('extended', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Создана'), ('waiting_for_capture', 'Ожидает подтверждения от пользователя'), ('succeeded', 'Подтверждена \\ активна'), ('canceled', 'Отменена')], default='pending', max_length=30, null=True),
        ),
    ]
