# Generated by Django 3.0.3 on 2020-02-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200209_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deal_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ID сделки в битрикс'),
        ),
    ]
