# Generated by Django 3.0.3 on 2020-02-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_deal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanness', models.IntegerField(blank=True, default=0, null=True, verbose_name='Чистота')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
            ],
            options={
                'verbose_name': 'Рейтинг заселения',
                'verbose_name_plural': 'Рейтинг заселений',
            },
        ),
    ]
