# Generated by Django 3.0.3 on 2020-02-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_bookingrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrate',
            name='staff',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Оценка работы персонала'),
        ),
    ]
