# Generated by Django 3.0.3 on 2020-02-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_bookingrate_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrate',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
