# Generated by Django 3.0.3 on 2020-02-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bookingrate_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Создана'), ('waiting_for_capture', 'Ожидает подтверждения от пользователя'), ('succeeded', 'Подтверждена \\ активна'), ('canceled', 'Отменена'), ('ended', 'Завершена')], default='pending', max_length=30, null=True),
        ),
    ]
