# Generated by Django 3.0.3 on 2020-02-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20200222_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end',
            field=models.DateTimeField(default=None, null=True, verbose_name='Окончание аренды'),
        ),
    ]
