# Generated by Django 3.0.3 on 2020-02-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrate',
            name='rated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
