# Generated by Django 3.0 on 2020-02-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, choices=[(False, 'Не показывается в каталоге'), (True, 'Показывается в каталоге')], null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('flat', models.CharField(blank=True, max_length=80, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, default=1, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hint', models.CharField(blank=True, max_length=50, null=True)),
                ('cleaning_time', models.TimeField(blank=True, default='3:00', null=True)),
                ('metro_station', models.CharField(blank=True, max_length=60, null=True)),
                ('bxcal_id', models.IntegerField(blank=True, default=None, null=True)),
                ('internal_id', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('img_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('urled', models.BooleanField(blank=True, default=False, null=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Flats')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='FlatsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Предмет (Стол, стул)')),
                ('item_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество предметов (целое число)')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Flats')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
    ]
