# Generated by Django 3.0 on 2020-02-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('managing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flats',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managing.Partners'),
        ),
    ]
