# Generated by Django 3.0 on 2020-02-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0002_partners_bitrix_url'),
        ('catalog', '0002_flats_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managing.Partners'),
        ),
    ]
