# Generated by Django 3.0.3 on 2020-02-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200204_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='cleaning_time',
            field=models.TimeField(blank=True, default='2:00', null=True),
        ),
    ]
