# Generated by Django 3.0.3 on 2020-02-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200209_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='hint',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FlatsRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanness', models.IntegerField(blank=True, default=0, null=True, verbose_name='Чистота')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Flats')),
            ],
            options={
                'verbose_name': 'Рейтинг квартиры',
                'verbose_name_plural': 'Рейтинг квартир',
            },
        ),
    ]
