# Generated by Django 3.0.3 on 2020-02-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200222_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlatsRate',
        ),
    ]
