# Generated by Django 3.0 on 2020-02-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='bitrix_url',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Ссылка фида в Bitrix'),
        ),
    ]
