# Generated by Django 3.0.3 on 2020-02-22 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0002_partners_bitrix_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='managing.Devices')),
            ],
        ),
    ]
