# Generated by Django 3.0.3 on 2020-02-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0003_systemlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='channel_name',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
